version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 11:d1:2b:f5:f5:d8:08:76:01:7b:14:af:0f:94:55:b5
            - 7d:e0:6b:e8:1e:11:46:a4:c6:3d:32:f0:a0:94:13:ca
      - run:
          name: Setup VirtualEnv and Build
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=servicio-esb' >> $BASH_ENV
            npm install
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to GCP via docker
          command: |
            ssh -o StrictHostKeyChecking=no re4lawliet@104.154.165.81 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"